//! Guided first-run setup (`open-interceptor setup`).
//!
//! Replaces the copy-paste dance of creating `config.yaml` by hand and then
//! remembering to install the daemon:
//!
//!   1. [`wizard`] collects the providers and credentials (ratatui).
//!   2. This module turns that into a validated [`Config`], writes it with
//!      owner-only permissions, and optionally installs + starts the daemon.
//!
//! Everything after the wizard runs on the normal terminal so failures stay
//! visible in scrollback.

use std::collections::HashMap;
use std::path::PathBuf;

use anyhow::Context;

use crate::daemon;
use crate::domain::config::{Config, Provider, Route};
use crate::services::config::ConfigService;

mod catalog;
mod wizard;

/// Where the daemon expects the config to live.
pub fn config_path() -> PathBuf {
    daemon::config_path()
}

/// Entry point for the `setup` subcommand.
pub async fn run(force: bool) -> anyhow::Result<()> {
    let path = config_path();

    if path.exists() && !force {
        println!("A config already exists at {}", path.display());
        println!();
        println!("  Re-run the wizard and overwrite it:  open-interceptor setup --force");
        println!(
            "  Or edit it directly:                 $EDITOR {}",
            path.display()
        );
        println!();
        println!("Daemon status:");
        daemon::status()?;
        return Ok(());
    }

    let Some(outcome) = wizard::run()? else {
        println!("Setup cancelled — nothing was written.");
        return Ok(());
    };

    apply(outcome, &path).await
}

/// Turn the wizard's answers into a config on disk and (optionally) a running
/// daemon.
async fn apply(outcome: wizard::Outcome, path: &std::path::Path) -> anyhow::Result<()> {
    let config = assemble(&outcome.selected, &outcome.values);

    // Catch a malformed catalog before touching the filesystem.
    config
        .validate()
        .context("the generated config failed validation (this is a bug in the setup catalog)")?;

    write_config(&config, path)?;
    println!("✓ config written to {}", path.display());

    // Re-read it the way the daemon will, so a broken file surfaces now and
    // not as a mysterious daemon that refuses to start.
    ConfigService::load(path).with_context(|| {
        format!(
            "the config written to {} could not be loaded back",
            path.display()
        )
    })?;
    println!("✓ config validated");

    if outcome.start_daemon {
        start_daemon()?;
    }

    print_next_steps(outcome.start_daemon);
    Ok(())
}

/// Build the `Config` from the selected catalog entries.
///
/// Route order is significant — the proxy takes the first match — so entry
/// routes are emitted in catalog order and the catch-all goes last.
fn assemble(selected: &[catalog::EntryKind], values: &HashMap<String, String>) -> Config {
    let mut providers: HashMap<String, Provider> = HashMap::new();
    let mut routes: Vec<Route> = Vec::new();

    for kind in selected {
        let (built_providers, built_routes) = catalog::build(*kind, values);
        for (name, provider) in built_providers {
            providers.insert(name, provider);
        }
        routes.extend(built_routes);
    }

    // A catch-all keeps unknown model ids working instead of erroring out.
    // Only Anthropic is a sensible default target, so it is added only when
    // that provider exists.
    if providers.contains_key("anthropic") {
        routes.push(Route {
            models: vec!["*".to_string()],
            provider: "anthropic".to_string(),
            remap: HashMap::new(),
        });
    }

    Config {
        port: daemon::PROXY_PORT,
        log_level: "info".to_string(),
        providers,
        routes,
        context_guard: None,
    }
}

/// Serialize and write the config, with a header comment and owner-only
/// permissions — it can hold API keys.
fn write_config(config: &Config, path: &std::path::Path) -> anyhow::Result<()> {
    let dir = path
        .parent()
        .context("config path has no parent directory")?;
    std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;

    let body = serde_yml::to_string(config).context("serializing the config")?;
    let contents = format!(
        "# open-interceptor configuration\n\
         #\n\
         # Generated by `open-interceptor setup`. Safe to edit by hand.\n\
         # Reference (all options, documented): \
         https://github.com/ragnito/open-interceptor/blob/master/config.yaml.example\n\
         #\n\
         # Secrets can be kept out of this file with ${{VAR}} syntax, e.g.\n\
         #   api_key: ${{OPENAI_API_KEY}}\n\
         #\n\
         # Apply changes with:  open-interceptor stop && open-interceptor start\n\
         \n\
         {body}"
    );

    std::fs::write(path, contents.as_bytes())
        .with_context(|| format!("writing {}", path.display()))?;

    // Best effort: on Unix keep the file owner-only since it may hold keys.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = std::fs::set_permissions(path, std::fs::Permissions::from_mode(0o600));
    }

    Ok(())
}

/// Install the service definition and start it, then wait for the port to
/// answer so "started" means the proxy is actually reachable.
fn start_daemon() -> anyhow::Result<()> {
    let exe = std::env::current_exe()
        .context("could not determine the path of the running executable")?;
    let exe = exe.canonicalize().unwrap_or(exe);

    // Stop first: re-running setup over a live daemon would otherwise fail to
    // bind the port, or keep serving the previous config.
    if daemon::is_installed() {
        let _ = daemon::stop();
    }

    daemon::install(&exe.to_string_lossy()).context("installing the daemon service")?;
    daemon::start().context("starting the daemon")?;

    let deadline = std::time::Instant::now() + std::time::Duration::from_secs(15);
    while std::time::Instant::now() < deadline {
        if daemon::probe() {
            println!(
                "✓ daemon running at http://127.0.0.1:{}",
                daemon::PROXY_PORT
            );
            return Ok(());
        }
        std::thread::sleep(std::time::Duration::from_millis(250));
    }

    // Not fatal: the config is written and the service is installed, so the
    // user can investigate without redoing the wizard.
    println!(
        "! daemon installed but port {} did not answer within 15 s",
        daemon::PROXY_PORT
    );
    println!("  check:  open-interceptor status");
    println!("  logs:   open-interceptor logs");
    Ok(())
}

fn print_next_steps(daemon_started: bool) {
    println!();
    println!("Next steps");
    if !daemon_started {
        println!("  Start the proxy:      open-interceptor start --install");
    }
    println!("  Run Claude Code:      open-interceptor claude");
    println!();
    println!("  …or point your shell at the proxy yourself:");
    println!(
        "    export ANTHROPIC_BASE_URL=http://127.0.0.1:{}",
        daemon::PROXY_PORT
    );
    println!("    export CLAUDE_CODE_ENABLE_GATEWAY_MODEL_DISCOVERY=1");
    println!();
    println!("Inside Claude Code, switch providers with  /model <name>");
}

#[cfg(test)]
mod tests {
    use super::*;
    use catalog::EntryKind;

    fn vals(pairs: &[(&str, &str)]) -> HashMap<String, String> {
        pairs
            .iter()
            .map(|(k, v)| ((*k).to_string(), (*v).to_string()))
            .collect()
    }

    #[test]
    fn anthropic_only_config_is_valid_and_has_a_catch_all_last() {
        let config = assemble(&[EntryKind::Anthropic], &HashMap::new());
        config.validate().expect("must be valid");
        assert_eq!(config.routes.last().unwrap().models, vec!["*"]);
        assert_eq!(config.routes.last().unwrap().provider, "anthropic");
    }

    #[test]
    fn without_anthropic_there_is_no_catch_all() {
        // A catch-all pointing at a provider the user did not configure would
        // send every unknown model to the wrong place.
        let config = assemble(&[EntryKind::OpenAi], &vals(&[("openai_key", "sk-x")]));
        config.validate().expect("must be valid");
        assert!(config.routes.iter().all(|r| r.models != vec!["*"]));
    }

    #[test]
    fn specific_routes_are_evaluated_before_the_catch_all() {
        let config = assemble(
            &[EntryKind::Anthropic, EntryKind::OpenAi],
            &vals(&[("openai_key", "sk-x")]),
        );
        let catch_all = config
            .routes
            .iter()
            .position(|r| r.models == vec!["*"])
            .expect("catch-all present");
        let openai = config
            .routes
            .iter()
            .position(|r| r.provider == "openai")
            .expect("openai route present");
        assert!(
            openai < catch_all,
            "specific routes must win over the catch-all"
        );
    }

    #[test]
    fn every_route_points_at_a_configured_provider() {
        let config = assemble(
            &[
                EntryKind::Anthropic,
                EntryKind::OpenCodeGo,
                EntryKind::OpenAi,
            ],
            &vals(&[("opencode_key", "sk-a"), ("openai_key", "sk-b")]),
        );
        config.validate().expect("all routes must resolve");
    }

    #[test]
    fn generated_config_round_trips_through_the_loader() {
        let config = assemble(&[EntryKind::Anthropic], &HashMap::new());
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yaml");
        write_config(&config, &path).unwrap();

        let loaded = ConfigService::load(&path).expect("written config must load back");
        assert_eq!(loaded.port, daemon::PROXY_PORT);
        assert!(loaded.providers.contains_key("anthropic"));
    }

    #[test]
    fn config_file_is_not_world_readable() {
        let config = assemble(&[EntryKind::OpenAi], &vals(&[("openai_key", "sk-secret")]));
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.yaml");
        write_config(&config, &path).unwrap();

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let mode = std::fs::metadata(&path).unwrap().permissions().mode();
            assert_eq!(mode & 0o077, 0, "config may hold API keys: {mode:o}");
        }
    }
}
